seed: 1919
wandb:
  project: "Mamba-CIFAR-10"
dataset:
  name: "CIFAR-10"
  _name_: "cifar"
  grayscale: True
train:
  num_epochs: 250
  batch_size: 64
  lr: 0.001
  wd: 0.01
  eta_min: 0.00005
model:
  layer: "mamba"
  num_blocks: 6
  input_dim: 1
  output_dim: 10
  hidden_dim: 128
  state_dim: 128
  conv_dim: 3
  expansion: 2
  dropout: 0.1
  glu: True
  norm: 'layer'
  dual: False
  prenorm: False
  pooling: "mean"
  bidirectional: True
  bidirectional_strategy: 'concat'
  tie_weights: False