seed: 2024
wandb:
  project: "Mamba-ListOps"
dataset:
  name: "listops"
  _name_: "listops"
train:
  num_epochs: 50
  batch_size: 64
  lr: 0.0001
  wd: 0.01
  eta_min: 0.00001
model:
  layer: "mamba"
  num_blocks: 8
  input_dim: 20
  output_dim: 10
  hidden_dim: 256
  state_dim: 128
  conv_dim: 3
  expansion: 2
  dropout: 0.1
  glu: True
  norm: 'layer'
  dual: False
  prenorm: True
  pooling: "mean"
  bidirectional: True
  bidirectional_strategy: 'concat'
  tie_weights: False
  tokenized_inputs: True
  mamba2: True